import {StyleSheet} from 'react-native';
import Colors from '../../../../utils/Colors';

const Income = StyleSheet.create({
  receivedPaymentForContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  receivedPaymentForCategoryContainer: {
    flex: 0.4875,
    justifyContent: 'center',
  },
  receivedPaymentForSubCategoryContainer: {
    flex: 0.4875,
    justifyContent: 'center',
  },
  dropdownCardLabelContainerStyle: {paddingHorizontal: 4},
  floatingTextInputCardContainer: {
    marginVertical: 8,
    paddingVertical: 2,
  },
  floatingTextInputContainer: {paddingBottom: 12},
  floatingTextInputLabel: {left: 4},
  floatingTextInput: {
    height: 36,
    top: 16,
    paddingHorizontal: 4,
    paddingVertical: 4,
  },
  dateTimeLabelStyle: {paddingHorizontal: 2},
  dateTimeValueStyle: {paddingHorizontal: 2},
  incomeDetailAccordionContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: Colors.sectionBar,
    paddingHorizontal: 20,
    paddingVertical: 8,
  },
  incomeDetailAccordionLabelContainer: {
    flex: 0.85,
    justifyContent: 'center',
  },
  incomeDetailAccordionImageContainer: {
    flex: 0.15,
    alignItems: 'center',
    justifyContent: 'center',
  },
  incomeDetailAccordionImage: {
    width: 20,
    height: 20,
    tintColor: Colors.primaryText,
  },
  incomeDetailContainer: {flex: 1, marginHorizontal: 20, marginVertical: 16},
  itemCategoryCardContainer: {
    flexDirection: 'column',
    marginVertical: 8,
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  itemContainer: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginHorizontal: 4,
    marginVertical: 8,
  },
  keyInItemContainer: {
    flexDirection: 'column',
    width: '50%',
    paddingHorizontal: 0,
    paddingVertical: 0,
  },
  rmContainer: {
    width: '35%',
    justifyContent: 'space-between',
    paddingHorizontal: 0,
    paddingVertical: 0,
  },
  rmLabelContainer: {
    width: '25%',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.barBackground,
    borderTopLeftRadius: 4,
    borderBottomLeftRadius: 4,
    paddingHorizontal: 4,
  },
  rmTextInputContainer: {
    width: '75%',
    justifyContent: 'center',
  },
  textInputContainer: {
    height: 32,
    color: Colors.darkElectricBlue,
    fontFamily: 'Proxima Nova',
    fontSize: 14,
    fontWeight: '400',
    paddingHorizontal: 8,
    paddingVertical: 0,
  },
  trashContainer: {
    width: 24,
    height: 24,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.background,
    borderColor: Colors.primary,
    borderStyle: 'dashed',
    borderWidth: 1,
    borderRadius: 24 / 2,
  },
  addItemButtonContainer: {
    width: '95%',
    alignSelf: 'center',
    borderColor: Colors.lightGrey,
    borderStyle: 'dashed',
    borderWidth: 1,
    elevation: 0,
  },
  totalContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 16,
    marginBottom: 8,
  },
  attachReceiptInvoiceButtonContainer: {
    borderColor: Colors.lightGrey,
    borderStyle: 'dashed',
    borderWidth: 1,
    marginTop: 16,
    elevation: 0,
  },
  attachmentViewContainer: {
    width: '100%',
    height: 240,
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: Colors.border,
    borderRadius: 8,
    borderWidth: 1,
    marginTop: 16,
  },
  attachmentView: {width: '100%', height: 236, borderRadius: 8},
  buttonCardContainer: {
    borderRadius: 0,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 4,
    shadowColor: Colors.dropShadow,
    shadowOffset: {
      width: 0,
      height: -2,
    },
    shadowRadius: 2,
  },
  buttonContainer: {width: '95%'},
  activityIndicator: {
    position: 'absolute',
    left: 0,
    top: 0,
    right: 0,
    bottom: 0,
  },
});

export default Income;
